services:
  lfs-builder:
    build: 
      context: .
      args:
        BUILDKIT_STEP_LOG_MAX_SIZE: 10485760
        BUILDKIT_STEP_LOG_MAX_SPEED: 10485760
    volumes:
      - ./workspace:/lfs-build/workspace
      - type: volume
        source: lfs_output
        target: /lfs-build/output
      - ./logs:/lfs-build/logs
      - /dev:/dev
      - /proc:/proc
      - /sys:/sys
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true  # Required for LFS build operations
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    tmpfs:
      - /tmp:exec,dev
      - /run:exec,dev
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    environment:
      BUILDKIT_PROGRESS: plain
      DOCKER_BUILDKIT: 1
      BUILDKIT_STEP_LOG_MAX_SIZE: 10485760
      COMPOSE_DOCKER_CLI_BUILD: 1
      VERBOSE: "true"
      PARALLEL_JOBS: 4  # Adjust based on your CPU cores
      BUILD_PROFILE: desktop_gnome
      GNOME_ENABLED: "true"
      NETWORKING_ENABLED: "true"
      CREATE_ISO: "true"
      LOG_PATH: /lfs-build/logs/build.log
      DEBUG: 1
      V: 1
      SHELL: "/bin/bash -x"
    tty: true  # Allocate a pseudo-TTY
    stdin_open: true  # Keep STDIN open
    networks:
      - lfs_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    develop:
      watch:
        - action: sync+restart
          path: ./lfs-build.sh
          target: /lfs-build/lfs-build.sh
        - action: sync
          path: ./workspace
          target: /lfs-build/workspace
        - action: sync
          path: ./logs
          target: /lfs-build/logs
          ignore:
            - "*.tmp"
            - "*.log"

volumes:
  lfs_output:
    name: lfs_output

networks:
  lfs_network:
    driver: bridge
