USB_SUPPORT="*"
HID_SUPPORT="*"
HID="*M"
INPUT="*"
INPUT_JOYSTICK="*"
JOYSTICK_GAMECON = { value = "*", comment = ["", "For older gamepads"] }
JOYSTICK_XPAD = { value = "*", comment = ["", "For Xbox gamepad support"] }
JOYSTICK_XPAD_FF=" *"
JOYSTICK_XPAD_LEDS=" *"
HID_NINTENDO = { value = "*", comment = ["", "For Nintendo Switch gamepad support"] }
NINTENDO_FF=" *"
HID_WIIMOTE = { value = " *M", comment = ["", "For Nintendo Wii and Wii U controller support"] }
HID_SONY = { value = "*M", comment = ["", "For Playstation gamepad support"] }
SONY_FF=" *"
HID_STEAM = { value = "*", comment = ["", "For Steam controllers"] }
