name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 lxml requests pytest

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texinfo binutils coreutils findutils diffutils \
            make bison flex gawk gcc g++ m4 sed grep patch \
            tar gzip xz-utils wget curl git

      - name: Run CI pipeline
        run: bash scripts/ci_pipeline.sh

      - name: Run unit tests
        run: |
          PYTHONWARNINGS="ignore::bs4.XMLParsedAsHTMLWarning" pytest
