name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install system requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bison flex gawk texinfo wget curl git patch
          
      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 lxml requests pytest
      - name: Run CI pipeline
        run: bash scripts/ci_pipeline.sh
      - name: Run unit tests
        run: bash tests/run_tests.sh
