name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run validation suite
        run: ENABLE_GNOME=false bash generated/validation_suite.sh
      - name: Run unit tests
        run: bash tests/run_tests.sh
